anaconda-post.log  bin  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  workspace
[root@debug-resnet-train-automodel /]# cd workspace/
[root@debug-resnet-train-automodel workspace]# ls
algicm  configs.json  docs  inference.py  input  output  README.md  rel_train.sh  test.py  tests  tmp  train.py  visual
[root@debug-resnet-train-automodel workspace]# python train.py --config configs.json
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    from algicm.engine.pytorch.runner import Runner
  File "/workspace/algicm/engine/__init__.py", line 6, in <module>
    from .common import (
  File "/workspace/algicm/engine/common/__init__.py", line 6, in <module>
    from .runner import (
  File "/workspace/algicm/engine/common/runner/__init__.py", line 6, in <module>
    from .runner import BaseRunner
  File "/workspace/algicm/engine/common/runner/runner.py", line 16, in <module>
    from .utils import random_data, merge_test_cfg, add_classes
  File "/workspace/algicm/engine/common/runner/utils.py", line 10, in <module>
    from algicm.models.backend.core import load_checkpoint
  File "/workspace/algicm/models/__init__.py", line 10, in <module>
    from .backend import BACKEND
  File "/workspace/algicm/models/backend/__init__.py", line 12, in <module>
    from .core.pytorch import *
  File "/workspace/algicm/models/backend/core/__init__.py", line 36, in <module>
    from .pytorch import (
  File "/workspace/algicm/models/backend/core/pytorch/__init__.py", line 1, in <module>
    from .base_module import BaseModule, Sequential, ModuleDict, ModuleList
  File "/workspace/algicm/models/backend/core/pytorch/base_module.py", line 13, in <module>
    from algicm.utils import Logger
  File "/workspace/algicm/utils/__init__.py", line 2, in <module>
    from .logger import Logger
  File "/workspace/algicm/utils/logger.py", line 14, in <module>
    from colorlog import ColoredFormatter
ModuleNotFoundError: No module named 'colorlog'
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]# python --version
Python 3.8.12
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]# pip install colorlog
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting colorlog
  Downloading colorlog-6.8.2-py3-none-any.whl (11 kB)
Installing collected packages: colorlog
Successfully installed colorlog-6.8.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]# python train.py --config configs.json
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    from algicm.engine.pytorch.runner import Runner
  File "/workspace/algicm/engine/__init__.py", line 6, in <module>
    from .common import (
  File "/workspace/algicm/engine/common/__init__.py", line 6, in <module>
    from .runner import (
  File "/workspace/algicm/engine/common/runner/__init__.py", line 6, in <module>
    from .runner import BaseRunner
  File "/workspace/algicm/engine/common/runner/runner.py", line 16, in <module>
    from .utils import random_data, merge_test_cfg, add_classes
  File "/workspace/algicm/engine/common/runner/utils.py", line 10, in <module>
    from algicm.models.backend.core import load_checkpoint
  File "/workspace/algicm/models/__init__.py", line 10, in <module>
    from .backend import BACKEND
  File "/workspace/algicm/models/backend/__init__.py", line 12, in <module>
    from .core.pytorch import *
  File "/workspace/algicm/models/backend/core/__init__.py", line 36, in <module>
    from .pytorch import (
  File "/workspace/algicm/models/backend/core/pytorch/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/workspace/algicm/models/backend/core/pytorch/base_model.py", line 10, in <module>
    from .data_processor import BaseDataProcessor
  File "/workspace/algicm/models/backend/core/pytorch/data_processor.py", line 9, in <module>
    from algicm.transform.transform import Compose
  File "/workspace/algicm/transform/__init__.py", line 9, in <module>
    from .transform import Resize, Normalize, TransposeImage, Stack, BertTokenizer
  File "/workspace/algicm/transform/transform/__init__.py", line 2, in <module>
    from .geometric import Resize, TransposeImage, PolygonsToMask
  File "/workspace/algicm/transform/transform/geometric.py", line 5, in <module>
    from algicm.transform.annotation import Mask, Polygon
  File "/workspace/algicm/transform/annotation/__init__.py", line 9, in <module>
    from .polygon import Polygon
  File "/workspace/algicm/transform/annotation/polygon.py", line 10, in <module>
    from shapely import geometry
ModuleNotFoundError: No module named 'shapely'
[root@debug-resnet-train-automodel workspace]# pip install shapely==

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement shapely== (from versions: 1.0a7, 1.0b1, 1.0b2, 1.0b3, 1.0b4, 1.0rc1, 1.0rc2, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.2b1, 1.2b2, 1.2b3, 1.2b4, 1.2b5, 1.2b6, 1.2b7, 1.2rc1, 1.2rc2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.12, 1.2.13, 1.2.14, 1.2.15, 1.2.16, 1.2.17, 1.2.18, 1.2.19, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.13, 1.5.14, 1.5.15, 1.5.16, 1.5.17, 1.6a1, 1.6a2, 1.6b1, 1.6b2, 1.6b3, 1.6b4, 1.6b5, 1.6.0, 1.6.1, 1.6.2, 1.6.2.post1, 1.6.3, 1.6.4, 1.6.4.post1, 1.6.4.post2, 1.7a1, 1.7a2, 1.7a3, 1.7b1, 1.7.0, 1.7.1, 1.8a1, 1.8a2, 1.8a3, 1.8rc1, 1.8rc2, 1.8.0, 1.8.1, 1.8.1.post1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.5.post1, 2.0a1, 2.0b1, 2.0b2, 2.0rc1, 2.0rc2, 2.0rc3, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4)
ERROR: No matching distribution found for shapely==

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]# pip install shapely==2.0.2
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting shapely==2.0.2
  Downloading shapely-2.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 1.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.8/site-packages (from shapely==2.0.2) (1.23.5)
Installing collected packages: shapely
Successfully installed shapely-2.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]# python train.py --config configs.json
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    from algicm.engine.pytorch.runner import Runner
  File "/workspace/algicm/engine/__init__.py", line 6, in <module>
    from .common import (
  File "/workspace/algicm/engine/common/__init__.py", line 6, in <module>
    from .runner import (
  File "/workspace/algicm/engine/common/runner/__init__.py", line 6, in <module>
    from .runner import BaseRunner
  File "/workspace/algicm/engine/common/runner/runner.py", line 16, in <module>
    from .utils import random_data, merge_test_cfg, add_classes
  File "/workspace/algicm/engine/common/runner/utils.py", line 10, in <module>
    from algicm.models.backend.core import load_checkpoint
  File "/workspace/algicm/models/__init__.py", line 10, in <module>
    from .backend import BACKEND
  File "/workspace/algicm/models/backend/__init__.py", line 12, in <module>
    from .core.pytorch import *
  File "/workspace/algicm/models/backend/core/__init__.py", line 36, in <module>
    from .pytorch import (
  File "/workspace/algicm/models/backend/core/pytorch/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/workspace/algicm/models/backend/core/pytorch/base_model.py", line 10, in <module>
    from .data_processor import BaseDataProcessor
  File "/workspace/algicm/models/backend/core/pytorch/data_processor.py", line 9, in <module>
    from algicm.transform.transform import Compose
  File "/workspace/algicm/transform/__init__.py", line 9, in <module>
    from .transform import Resize, Normalize, TransposeImage, Stack, BertTokenizer
  File "/workspace/algicm/transform/transform/__init__.py", line 10, in <module>
    from .txt_transform import (
  File "/workspace/algicm/transform/transform/txt_transform.py", line 2, in <module>
    import jieba
ModuleNotFoundError: No module named 'jieba'
[root@debug-resnet-train-automodel workspace]# pip install jieba 0.42.1
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting jieba
  Downloading jieba-0.42.1.tar.gz (19.2 MB)
     ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━ 8.9/19.2 MB 1.2 MB/s eta 0:00:09
ERROR: Operation cancelled by user
^[[A^CTraceback (most recent call last):
  File "/usr/local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 190, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py", line 227, in pip_self_version_check
    upgrade_prompt = _self_version_check_logic(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py", line 193, in _self_version_check_logic
    remote_version_str = get_remote_version()
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py", line 177, in _get_current_remote_pip_version
    best_candidate = finder.find_best_candidate("pip").best_candidate
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 889, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 830, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/index/sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 790, in process_project_url
    index_response = self._link_collector.fetch_response(project_url)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 461, in fetch_response
    return _get_index_content(location, session=self.session)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 364, in _get_index_content
    resp = _get_simple_response(url, session=session)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 135, in _get_simple_response
    resp = session.get(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 518, in request
    return super().request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt

[root@debug-resnet-train-automodel workspace]# ^C
[root@debug-resnet-train-automodel workspace]# pip install jieba==0.42.1
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting jieba==0.42.1
  Downloading jieba-0.42.1.tar.gz (19.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: jieba
  Building wheel for jieba (setup.py) ... done
  Created wheel for jieba: filename=jieba-0.42.1-py3-none-any.whl size=19314477 sha256=7e418fe86abf7783ed45d7ed95c32a5499bbaa2081a5760b9c933269b349acc9
  Stored in directory: /tmp/pip-ephem-wheel-cache-jfi_vujd/wheels/10/a7/21/b0ced8222c9b5e1eae11b7d13d40d028786c5e57e4c604c5da
Successfully built jieba
Installing collected packages: jieba
Successfully installed jieba-0.42.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]# python train.py --config configs.json
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    from algicm.engine.pytorch.runner import Runner
  File "/workspace/algicm/engine/__init__.py", line 6, in <module>
    from .common import (
  File "/workspace/algicm/engine/common/__init__.py", line 6, in <module>
    from .runner import (
  File "/workspace/algicm/engine/common/runner/__init__.py", line 6, in <module>
    from .runner import BaseRunner
  File "/workspace/algicm/engine/common/runner/runner.py", line 16, in <module>
    from .utils import random_data, merge_test_cfg, add_classes
  File "/workspace/algicm/engine/common/runner/utils.py", line 10, in <module>
    from algicm.models.backend.core import load_checkpoint
  File "/workspace/algicm/models/__init__.py", line 10, in <module>
    from .backend import BACKEND
  File "/workspace/algicm/models/backend/__init__.py", line 12, in <module>
    from .core.pytorch import *
  File "/workspace/algicm/models/backend/core/__init__.py", line 36, in <module>
    from .pytorch import (
  File "/workspace/algicm/models/backend/core/pytorch/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/workspace/algicm/models/backend/core/pytorch/base_model.py", line 10, in <module>
    from .data_processor import BaseDataProcessor
  File "/workspace/algicm/models/backend/core/pytorch/data_processor.py", line 9, in <module>
    from algicm.transform.transform import Compose
  File "/workspace/algicm/transform/__init__.py", line 10, in <module>
    from .format import (
  File "/workspace/algicm/transform/format/__init__.py", line 15, in <module>
    from .http_formatter import (
  File "/workspace/algicm/transform/format/http_formatter.py", line 15, in <module>
    from flask import request
ModuleNotFoundError: No module named 'flask'
[root@debug-resnet-train-automodel workspace]# pip install flask==
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement flask== (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.10, 0.10.1, 0.11, 0.11.1, 0.12, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 3.0.0, 3.0.1, 3.0.2, 3.0.3)
ERROR: No matching distribution found for flask==

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]# pip install flask==3.0.3
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting flask==3.0.3
  Downloading flask-3.0.3-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 821.4 kB/s eta 0:00:00
Collecting click>=8.1.3
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 3.4 MB/s eta 0:00:00
Collecting Werkzeug>=3.0.0
  Downloading werkzeug-3.0.3-py3-none-any.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.3/227.3 kB 2.2 MB/s eta 0:00:00
Collecting Jinja2>=3.1.2
  Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.3/133.3 kB 8.9 MB/s eta 0:00:00
Requirement already satisfied: importlib-metadata>=3.6.0 in /usr/local/lib/python3.8/site-packages (from flask==3.0.3) (5.1.0)
Collecting itsdangerous>=2.1.2
  Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Collecting blinker>=1.6.2
  Downloading blinker-1.8.2-py3-none-any.whl (9.5 kB)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/site-packages (from importlib-metadata>=3.6.0->flask==3.0.3) (3.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/site-packages (from Jinja2>=3.1.2->flask==3.0.3) (2.1.1)
Installing collected packages: Werkzeug, Jinja2, itsdangerous, click, blinker, flask
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 2.2.2
    Uninstalling Werkzeug-2.2.2:
      Successfully uninstalled Werkzeug-2.2.2
Successfully installed Jinja2-3.1.4 Werkzeug-3.0.3 blinker-1.8.2 click-8.1.7 flask-3.0.3 itsdangerous-2.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]# python train.py --config configs.json
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    from algicm.engine.pytorch.runner import Runner
  File "/workspace/algicm/engine/__init__.py", line 6, in <module>
    from .common import (
  File "/workspace/algicm/engine/common/__init__.py", line 6, in <module>
    from .runner import (
  File "/workspace/algicm/engine/common/runner/__init__.py", line 6, in <module>
    from .runner import BaseRunner
  File "/workspace/algicm/engine/common/runner/runner.py", line 22, in <module>
    from ..hooks import Hook
  File "/workspace/algicm/engine/common/hooks/__init__.py", line 14, in <module>
    from .transfer_station_hook import TransferStationHook
  File "/workspace/algicm/engine/common/hooks/transfer_station_hook.py", line 14, in <module>
    from algicm.engine.common.message.kafka_station import KafkaStation
  File "/workspace/algicm/engine/common/message/kafka_station.py", line 17, in <module>
    from confluent_kafka import Producer
ModuleNotFoundError: No module named 'confluent_kafka'
[root@debug-resnet-train-automodel workspace]# pip install confluent-kafka==
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement confluent-kafka== (from versions: 0.9.1.1, 0.9.1.2, 0.9.2, 0.9.4, 0.11.0, 0.11.4, 0.11.5, 0.11.6, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.6.0, 1.6.1, 1.7.0, 1.8.2, 1.9.0, 1.9.2, 2.0.2, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.4.0)
ERROR: No matching distribution found for confluent-kafka==

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]# pip install confluent-kafka==1.9.2
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting confluent-kafka==1.9.2
  Downloading confluent_kafka-1.9.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 1.2 MB/s eta 0:00:00
Installing collected packages: confluent-kafka
Successfully installed confluent-kafka-1.9.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]# python train.py --config configs.json
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    from algicm.engine.pytorch.runner import Runner
  File "/workspace/algicm/engine/__init__.py", line 6, in <module>
    from .common import (
  File "/workspace/algicm/engine/common/__init__.py", line 6, in <module>
    from .runner import (
  File "/workspace/algicm/engine/common/runner/__init__.py", line 6, in <module>
    from .runner import BaseRunner
  File "/workspace/algicm/engine/common/runner/runner.py", line 28, in <module>
    from algicm.datasets import DataLoader, BaseDataset
  File "/workspace/algicm/datasets/__init__.py", line 8, in <module>
    from .cv import CIFAR10, MNIST, COCODatasets, ClsDataset, DetDataset, SegDataset
  File "/workspace/algicm/datasets/cv/__init__.py", line 2, in <module>
    from .det import COCODatasets,DetDataset
  File "/workspace/algicm/datasets/cv/det/__init__.py", line 6, in <module>
    from .coco import COCODatasets
  File "/workspace/algicm/datasets/cv/det/coco.py", line 11, in <module>
    import pycocotools
ModuleNotFoundError: No module named 'pycocotools'
[root@debug-resnet-train-automodel workspace]# pip install pycocotools==
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement pycocotools== (from versions: 2.0.0, 2.0.1, 2.0.2a1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7)
ERROR: No matching distribution found for pycocotools==

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]# pip install pycocotools==2.0.7
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pycocotools==2.0.7
  Downloading pycocotools-2.0.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 kB 851.1 kB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.8/site-packages (from pycocotools==2.0.7) (1.23.5)
Requirement already satisfied: matplotlib>=2.1.0 in /usr/local/lib/python3.8/site-packages (from pycocotools==2.0.7) (3.6.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.7) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.7) (1.0.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.7) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.7) (9.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.7) (22.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.7) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.7) (4.38.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.7) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->pycocotools==2.0.7) (1.16.0)
Installing collected packages: pycocotools
Successfully installed pycocotools-2.0.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]# python train.py --config configs.json
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    from algicm.engine.pytorch.runner import Runner
  File "/workspace/algicm/engine/pytorch/__init__.py", line 6, in <module>
    from .runner import Runner
  File "/workspace/algicm/engine/pytorch/runner/__init__.py", line 6, in <module>
    from .runner import Runner
  File "/workspace/algicm/engine/pytorch/runner/runner.py", line 14, in <module>
    import horovod.torch as hvd
ModuleNotFoundError: No module named 'horovod'
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]# pip install horovod==
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement horovod== (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.10, 0.13.11, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.18.0, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.19.5, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22.0, 0.22.1, 0.23.0, 0.24.0, 0.24.1, 0.24.2, 0.24.3, 0.25.0, 0.26.0, 0.26.1, 0.27.0, 0.28.0, 0.28.1)
ERROR: No matching distribution found for horovod==

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]# pip install horovod==0.28.1
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting horovod==0.28.1
  Downloading horovod-0.28.1.tar.gz (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting cloudpickle
  Downloading cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.8/site-packages (from horovod==0.28.1) (5.9.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.8/site-packages (from horovod==0.28.1) (6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/site-packages (from horovod==0.28.1) (22.0)
Collecting cffi>=1.4.0
  Downloading cffi-1.16.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (444 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 444.7/444.7 kB 1.3 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.22-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 1.4 MB/s eta 0:00:00
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... done
  Created wheel for horovod: filename=horovod-0.28.1-cp38-cp38-linux_x86_64.whl size=15418374 sha256=8fcf601fcf1729b6221b666254631ce30db0765cd8f3d77e992ed22fd8335d51
  Stored in directory: /tmp/pip-ephem-wheel-cache-74rztro8/wheels/28/c3/3c/9c9e3056c044a77f0a0e32a4025146bc25ca0a1a832a5f10eb
Successfully built horovod
Installing collected packages: pycparser, cloudpickle, cffi, horovod
Successfully installed cffi-1.16.0 cloudpickle-3.0.0 horovod-0.28.1 pycparser-2.22
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]#
[root@debug-resnet-train-automodel workspace]# python train.py --config configs.json


^CTraceback (most recent call last):
  File "train.py", line 34, in <module>
    from algicm.engine.pytorch.runner import Runner
  File "/workspace/algicm/engine/__init__.py", line 6, in <module>
    from .common import (
  File "/workspace/algicm/engine/common/__init__.py", line 6, in <module>
    from .runner import (
  File "/workspace/algicm/engine/common/runner/__init__.py", line 6, in <module>
    from .runner import BaseRunner
  File "/workspace/algicm/engine/common/runner/runner.py", line 16, in <module>
    from .utils import random_data, merge_test_cfg, add_classes
  File "/workspace/algicm/engine/common/runner/utils.py", line 10, in <module>
    from algicm.models.backend.core import load_checkpoint
  File "/workspace/algicm/models/__init__.py", line 10, in <module>
    from .backend import BACKEND
  File "/workspace/algicm/models/backend/__init__.py", line 12, in <module>
    from .core.pytorch import *
  File "/workspace/algicm/models/backend/core/__init__.py", line 36, in <module>
    from .pytorch import (
  File "/workspace/algicm/models/backend/core/pytorch/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/workspace/algicm/models/backend/core/pytorch/base_model.py", line 10, in <module>
    from .data_processor import BaseDataProcessor
  File "/workspace/algicm/models/backend/core/pytorch/data_processor.py", line 9, in <module>
    from algicm.transform.transform import Compose
  File "/workspace/algicm/transform/__init__.py", line 10, in <module>
    from .format import (
  File "/workspace/algicm/transform/format/__init__.py", line 15, in <module>
    from .http_formatter import (
  File "/workspace/algicm/transform/format/http_formatter.py", line 18, in <module>
    from algicm.service.utils import wrap_jsonify
  File "/workspace/algicm/service/utils.py", line 11, in <module>
    from algicm.fileio.handler.json_handler import JsonHandler
  File "/workspace/algicm/fileio/handler/__init__.py", line 6, in <module>
    from .builder import file_handlers
  File "/workspace/algicm/fileio/handler/builder.py", line 6, in <module>
    from .yaml_handler import YamlHandler
  File "/workspace/algicm/fileio/handler/yaml_handler.py", line 2, in <module>
    import yaml
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 8, in <module>
    from .loader import *
  File "/usr/local/lib/python3.8/site-packages/yaml/loader.py", line 9, in <module>
    from .resolver import *
  File "/usr/local/lib/python3.8/site-packages/yaml/resolver.py", line 209, in <module>
    re.compile(r'''^(?:[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]
  File "/usr/local/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.8/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/local/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.8/sre_parse.py", line 693, in _parse
    char = sourceget()
  File "/usr/local/lib/python3.8/sre_parse.py", line 256, in get
    self.__next()
KeyboardInterrupt

[root@debug-resnet-train-automodel workspace]# hcommand terminated with exit code 137
[root@dcu debug_icm_train-automodel]# k exec -it -n icaplat-sit-train-automodel debug-resnet-train-automodel -- /bin/bash
error: cannot exec into a container in a completed pod; current phase is Succeeded
[root@dcu debug_icm_train-automodel]# ls
resnet_train-automodel.yaml
[root@dcu debug_icm_train-automodel]# kda resnet_train-automodel.yaml
pod "debug-resnet-train-automodel" deleted


pod/debug-resnet-train-automodel created
[root@dcu debug_icm_train-automodel]#
